apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: k6-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system   
